variables:
  DOCKER_REPOSITORY: mendersoftware/mender-ci-tools

stages:
  - test
  - build
  - publish
  - trigger

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-docker-build.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

trigger:docs-site:
  stage: trigger
  image: alpine
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|hosted|[0-9]+\.[0-9]+\.x)$/
      changes:
        paths:
          - docs/*
  before_script:
    - apk add --no-cache curl
  script:
    - curl -v -f -X POST
      -F token=$MENDER_DOCS_SITE_TRIGGER_TOKEN
      -F ref=master
      https://gitlab.com/api/v4/projects/16842368/trigger/pipeline
    - curl -v -f -X POST
      -F token=$MENDER_DOCS_SITE_TRIGGER_TOKEN
      -F ref=production
      https://gitlab.com/api/v4/projects/16842368/trigger/pipeline
