# GitLab CI template to build Mender artifacts.
#
# The template is designed to be used with the includes keyword or copied into an existing
# configuration. It can be used to build a Mender artifact in the `script` section. 
# `before_script` is used for creating the `MENDER_ARTIFACTS_FOLDER` folder. If it's overwritten,
# then make sure your script contains this step.
#
# Mender artifacts in the `MENDER_ARTIFACTS_FOLDER` folder will be uploaded as GitLab CI artifacts
# and shared across jobs in a pipeline.

include:
  - project: 'Northern.tech/Mender/mender-ci-workflows'
    file: 'templates/gitlab/common.gitlab-ci.yml'
    ref: 'master'

.mender:build:artifact:
  image: mendersoftware/mender-ci-tools:1.0.0
  before_script:
    - if [ ! -d ${MENDER_ARTIFACTS_FOLDER} ]; then mkdir -p ${MENDER_ARTIFACTS_FOLDER}; fi
  script:
    # to be overwritten after the job is inherited
    - echo "Please override the script keyword in your job"
    - exit 1
  artifacts:
    expire_in: 1w
    paths:
      - ${MENDER_ARTIFACTS_FOLDER}/*
